# Generated by Django 3.0.8 on 2021-05-17 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200730_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='processor_freq',
            field=models.CharField(default=datetime.date.today, max_length=255, verbose_name='Частота процессора'),
            preserve_default=False,
        ),
    ]
