# Generated by Django 3.0.8 on 2021-05-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_smartphone_processor_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='processor_freq',
        ),
    ]
