# Generated by Django 3.0.8 on 2021-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_desktop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='time_without_charge',
        ),
        migrations.AddField(
            model_name='desktop',
            name='block_pitania',
            field=models.CharField(default=0, max_length=255, verbose_name='Блок питания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desktop',
            name='model_proc',
            field=models.CharField(default=0, max_length=255, verbose_name='Модель Процессора'),
            preserve_default=False,
        ),
    ]
