# Generated by Django 3.0.8 on 2021-05-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_appliances_audio_office_photographic_software_television'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='sd',
            field=models.CharField(max_length=255, verbose_name='Длина шнура'),
        ),
        migrations.AlterField(
            model_name='office',
            name='garantiya',
            field=models.CharField(max_length=255, verbose_name='Гарантийный срок'),
        ),
    ]
